#
#   Copyright (c)  2007             Dmitry Butskoy
#                                   <dmitry@butskoy.name>
#   License:  GPL v2 or any later
#
#   See COPYING for the status of this software.
#

#
#   Nothing to do.
#

all depend install:
	@true

